# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Card": "00_card.ipynb",
         "Deck": "01_deck.ipynb"}

modules = ["card.py",
           "deck.py"]

doc_url = "https://sflinter.github.io/deck_of_cards_new/"

git_url = "https://github.com/sflinter/deck_of_cards_new/tree/master/"

def custom_doc_links(name): return None
